wsgi/django_foodcoop/urls.py
from django.conf.urls import patterns, include, url
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r"^$", never_cache(TemplateView.as_view(template_name="homepage.html")), name="home"),

    url(r"^account/", include("account.urls")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^foodcoop/', include('foodcoop.urls')),

    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^upcoming/$', 'django.contrib.flatpages.views.flatpage', {'url': '/upcoming/'}, name='upcoming'),
    url(r'^announcesale/$', 'django.contrib.flatpages.views.flatpage', {'url': '/announcesale/'}, name='announcesale'),
#    url(r'^cache-manifest/$', 'django_foodcoop.views.cache_manifest', name='cache-manifest'),
#    url(r'^offline/$', TemplateView.as_view(template_name="offline.html"), name='offline-fallback'),
#    url(r'^cache-manifest/$', CacheManifestView.as_view(), name='cache-manifest'),
)

wsgi/django_foodcoop/foodcoop/models.py
# -*- coding: utf-8 -*-
import decimal

from django.db import models
from django.db.models import F, Q
from django.db.models.query import QuerySet
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
 
VALUE_ADDED_TAX_RATIO = decimal.Decimal('1.18')
SELLING_PRICE_RATIO = decimal.Decimal('1.05')

__all__ = (
    'Sale', 'UserProfile', 'ProductOrder', 'ProductFinalOrder', 'Product',
    'Transfer', 'Payment', 'Supplier', 'SaleProduct', 'ChequePayment',
    'Unit', 'ChequeEnvelope', 'SaleStaffMember', 'Person', 'TransferType',
    'SupplierCategory', 'PaymentToSupplier', 'OtherPayment', 'Tariff',
    'VALUE_ADDED_TAX_RATIO', 'SELLING_PRICE_RATIO',
    'METHOD_CASH', 'METHOD_CHEQUE', 'METHOD_BANK_TRANSFER',
)

class Tariff(models.Model):
    '''
    Tariff type
    '''
    type = models.CharField(max_length=25)
    factor = models.DecimalField(max_digits=10, decimal_places=2)

    def __unicode__(self):
        return self.type

class CustomQuerySetManager(models.Manager):
    """A re-usable Manager to access a custom QuerySet - taken from http://stackoverflow.com/a/2163921"""
    def __getattr__(self, attr, *args):
        try:
            return getattr(self.__class__, attr, *args)
        except AttributeError:
            return getattr(self.get_query_set(), attr, *args)

    def get_query_set(self):
        return self.model.QuerySet(self.model)

def decimal_field(max_digits=10, decimal_places=2, **kwargs):
    return models.DecimalField(max_digits=max_digits, decimal_places=decimal_places, **kwargs)

class UserProfile(models.Model):  
    DEFAULT_SHARE_PRICE = 300
    user = models.ForeignKey(User, unique=True)
    user_number = models.IntegerField(unique=True, null=True, blank=True)
    joined_at = models.DateField(null=True, blank=True)
    left_at = models.DateField(null=True, blank=True)
    bought_share_at = models.DateField(null=True, blank=True)
    share_price = decimal_field(default=DEFAULT_SHARE_PRICE, null=True, blank=True)
    tariff = models.ForeignKey(Tariff)

    def __unicode__(self):
        return unicode(self.user)

    def contact_details(self):
        info = []
        for person in self.user.persons.all():
            person_info = ' / '.join([str(d) for d in [person.cellular_phone_number, person.home_phone_number] if d])
            if person_info:
                info.append('%s: %s' %(person.name, person_info))
        return info

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a matching profile whenever a User is created."""
    if created and not kwargs.get('raw', False):
        UserProfile.objects.get_or_create(user=instance)

class Person(models.Model):
    '''
    A user represents a household which is a member of the cooperative.
    Person links to the individuals, who may have different names, phone numbers, etc.
    '''   
    user = models.ForeignKey(User, related_name='persons')
    name = models.CharField(max_length=50, unique=True)
    home_phone_number = models.CharField(max_length=20, blank=True, null=False)
    cellular_phone_number = models.CharField(max_length=20, blank=True, null=False)
    email_address = models.EmailField(blank=True, null=False)

    def __unicode__(self):
        return self.name

class SaleManager(models.Manager):
    def latest_by_status(self, status):
        '''
        Get the latest sale according to a given status (open to buyers, open to all, etc.) if exists.
        Otherwise return None.
        '''
        sales = self.filter(status__exact=status).order_by("-sale_date")[:1]
        return None if len(sales) == 0 else sales[0]

    def latest_open_to_buyers(self):
        return self.latest_by_status(Sale.OPEN_TO_BUYERS)

    def latest_open_to_all(self):
        return self.latest_by_status(Sale.OPEN_TO_ALL)

    def latest_draft(self):
        return self.latest_by_status(Sale.DRAFT)

    def latest_ready(self):
        return self.latest_by_status(Sale.FINAL)

    def archived(self):
        return self.filter(status__in=[Sale.FINAL, Sale.CLOSED]).order_by('-sale_date')

class Sale(models.Model):
    '''
    Sale life cycle:
    1) created by admin as OPEN_TO_BUYERS and informs buyers
    2) all buyers edit their suppliers product list, and inform admin
    3) admin changes status to OPEN_TO_ALL and informs members
    4) all members edit their orders
    5) admin changes status to DRAFT and informs buyers
    6) (TODO: needs re-thinking) manually fix orders to comply with restrictions, such as package sizes
    7) sale is ready - admin changes status to FINAL
    8) after sale is really over, admin changes to CLOSED
    '''
    OPEN_TO_BUYERS = 'open_to_buyers'
    OPEN_TO_ALL    = 'open_to_all'
    DRAFT          = 'draft'
    FINAL          = 'final'
    CLOSED         = 'closed'
    STATUS_CHOICES = [(x,x) for x in (OPEN_TO_BUYERS, OPEN_TO_ALL, DRAFT, FINAL, CLOSED)]
    
    title = models.CharField(max_length=50)
    sale_date = models.DateTimeField()
    closing_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=15, default=OPEN_TO_BUYERS, choices=STATUS_CHOICES)
    comments = models.TextField(verbose_name='הערות')

    objects = SaleManager()

    def is_open_to_buyers(self):
        return (self.status == Sale.OPEN_TO_BUYERS)
    
    def is_open(self):
        return (self.status == Sale.OPEN_TO_ALL)

    def is_draft(self):
        return (self.status == Sale.DRAFT)
    
    def is_finalized(self):
        return (self.status == Sale.FINAL)

    def is_closed(self):
        return (self.status == Sale.CLOSED)

    def __unicode__(self):
        return self.title

    def get_product_statistics(self):
        categories = []
        for supplier in Supplier.objects.select_related().all():
            if supplier.has_categories():
                for supplier_category in supplier.suppliercategory_set.all():
                    categories.append({
                        'name': supplier_category.name,
                        'num_products': self.saleproduct_set.filter(product__category=supplier_category).count(),
                    })
            else:
                categories.append({
                    'name': supplier.name,
                    'num_products': self.saleproduct_set.filter(product__supplier=supplier).count(),
                })
        return categories
        
class SaleStaffMember(models.Model):
    MANAGER = 'manager'
    # TODO: rename HELPER, maybe rename REGISTER
    REGISTER = 'register'
    HELPER = 'helper'
    
    ROLE_CHOICES = (
        (MANAGER, 'sale day manager'),
        (REGISTER, 'working the register'),
        (HELPER, 'helping everyone'),
    )
    
    sale = models.ForeignKey(Sale, related_name='staff_members')
    member = models.ForeignKey(User)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)

class Supplier(models.Model):
    name = models.CharField(max_length=100)
    buyers = models.ManyToManyField(User, blank=True)

    def has_categories(self):
        return (self.suppliercategory_set.count() > 0)

    def __unicode__(self):
        return self.name

class SupplierCategory(models.Model):
    name = models.CharField(max_length=100)
    supplier = models.ForeignKey(Supplier, verbose_name='ספק')
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'supplier categories'

class Unit(models.Model):
    '''
    Common units for products. Examples: 1 kg, 100 grams, bundle, etc.
    '''
    unit = models.CharField(max_length=25)

    def __unicode__(self):
        return self.unit


class ProductManager(models.Manager):
    def get_query_set(self):
        '''
        Get all related objects by default
        '''
        return super(ProductManager, self).get_query_set().select_related('supplier', 'unit').order_by('name')

class Product(models.Model):
    PACKAGED_CHOICES = (
        (0, u'תפזורת'),
        (1, u'ארוז')
    )
    ORGANIC_CHOICES = (
        (0, u'לא אורגני'),
        (1, u'אורגני'),
    )
    
    name = models.CharField(max_length=100, verbose_name='שם המוצר')
    supplier = models.ForeignKey(Supplier, verbose_name='ספק')
    category = models.ForeignKey(SupplierCategory, verbose_name='קטגוריה', null=True, blank=True)
    unit = models.ForeignKey(Unit, verbose_name='יחידה')
    price_before_VAT = decimal_field(null=True, blank=True, verbose_name='מחיר ללא מע"מ')
    price_including_VAT = decimal_field(null=True, blank=True, verbose_name='מחיר כולל מע"מ')
    packaged = models.SmallIntegerField(verbose_name='ארוז/תפזורת', choices=PACKAGED_CHOICES)
    organic  = models.SmallIntegerField(verbose_name='אורגני', choices=ORGANIC_CHOICES)
    package_size = decimal_field(verbose_name='גודל אריזה')                             # all values are integer
    description = models.TextField(blank=True, null=False, verbose_name='תיאור')
    inventory = decimal_field(null=True, blank=True, verbose_name='מלאי')
    deleted = models.BooleanField(default=False)

    objects = ProductManager()
#    all_objects = models.Manager() # TODO: use this in admin page 
    
    class Meta:
        pass
        #unique_together = (('supplier', 'name'),)

    def __unicode__(self):
        return self.name

    def delete(self):
        self.deleted = True # TODO: hook to pre_delete or post_delete signals instead 
        self.save()

    def create_new_sale_product(self, sale):
        return SaleProduct(product=self, sale=sale, price=0, price_before_VAT=self.price_before_VAT,
                           price_including_VAT=self.price_including_VAT, package_size=self.package_size)

# TODO: fix this. currently hack to make things work, using after_VAT price as the single source of truth
@receiver(pre_save, sender=Product)
def calc_product_prices(sender, instance, **kwargs):

wsgi/django_foodcoop/templates/members/final_order_list.html
{% extends "site_base.html" %}

{% load foodcoop_extras %}

{% block extra_head %}
<script type="text/javascript">
jQ(document).ready(function() {
	jQ.each(jQ('td.product_quantity'), hack_quantity_field_value);

	sumElements(jQ('td.total_price'), jQ('th#total'));
	
	jQ('#id_order_table').dataTable({
		"bSort": false,
		"aLengthMenu": [[-1], ["All"]],
	    "iDisplayLength": -1,
	    "sDom": 't',
	});
});
</script>
{% endblock %}

{% block body %}
<div class="noprint">
	<h3>הזמנה סופית לחבר/ה</h3>
	<h4>מכירה: {{ sale }}</h4>
	<h4>חבר/ה: {{ member.get_full_name }}</h4>
	<input type="button" class="btn" value="הדפסה" onclick="window.print();">
</div>

<table id="id_order_table">
	<thead>
		<tr>
			<th class="noprint"></th>
			<th>מוצר</th>
			<th>ספק</th>
			<th class="noprint">יחידה</th>
			<th class="noprint">מחיר ליחידה</th>
			<th class="noprint">כמות שהוזמנה</th>
			<th>כמות מתוקנת</th>
			{% if epilogue %}
			<th>כמות ששולמה בקופה</th>
			{% endif %}
			<th>מחיר</th>
		</tr>
	</thead>
	<tbody>
		{% for final_order in object_list %}
			{% with final_order.product_order as order %}
				{% with order.product as product %}
				<tr>
					<td class="noprint">{{ forloop.counter }}</td>
					<td>{{ product.name }}</td>
					<td>{{ product.product.supplier }}</td>
					<td class="noprint">{{ product.product.unit }}</td>
					<td class="noprint">{{ product.price }}</td>
					<td class="noprint">{{ order.amount }}</td>
					{% if epilogue %}
					<td class="product_quantity">{{ final_order.amount }}</td>
					<td class="product_quantity final_amount">{{ final_order.amount_bought }}</td>
					<td class="total_price">{{ final_order.total_price_bought }}</td>
					{% else %}
					<td class="product_quantity final_amount">{{ final_order.amount }}</td>
					<td class="total_price">{{ final_order.total_price }}</td>
					{% endif %}
				</tr>
				{% endwith %}
			{% endwith %}
		{% endfor %}
		<tr>
			<th class="noprint"></th>
			<th>סה"כ</th>
			<th></th>
			<th class="noprint"></th>
			<th class="noprint"></th>
			<th class="noprint"></th>
			<th></th>
			{% if epilogue %}
			<th></th>
			{% endif %}
			<th id="total"></th>
		</tr>
	</tbody>
</table>
{% endblock %}

wsgi/django_foodcoop/templates/members/member_order_form.html
{% extends "site_base.html" %}

{% load staticfiles %}
{% load foodcoop_extras %}
{% block head_title %}{{ sale }}{% endblock %}

{% block extra_head %}
<style>
table td.description {
	width: 250px;
}
select, input[type=text] {
	width: 40px;
}
textarea {
	width: 180px;
	height: 20px;
}
</style>
<script>
jQ(function() {
	jQ("#accordion").accordion({
	 collapsible: true
	});
 	jQ("#id_member_order_table").dataTable({
		"bSort": false,
		"aLengthMenu": [[-1], ["All"]],
	    "iDisplayLength": -1,
	    "sDom": 't',
	});
 	jQ.each(jQ("tr.product"), function(index, elem) {
 		package_size = parseFloat(jQ(elem).find('td.package_size').html());
 		if (package_size == 1) {
 			jQ(elem).find('input.conditional_disable').prop("readonly", true);
 		}
 	});
});
</script>

</script>
{% endblock %}

{% block body %}
	<h3>עריכת הזמנה</h3>
	<h4>מכירה: {{ sale }}</h4>
	<div id="accordion">
		<h3>הערות</h3>
		<div class="row">
			<iframe width="100%" height="350px" src="/announcesale/" frameBorder="0"></iframe>
		</div>
	</div>
	
    <form method="post" action="">
    {% csrf_token %}
    {% if formset.non_field_errors or formset.errors %}
    <p class="errornote">Please correct the errors below</p>
    {{ formset.non_field_errors.as_ul }}
	{% endif %}
    
    	{# taken from http://djangosnippets.org/snippets/1442/ #}
		<table id="id_member_order_table" class="form" border="1">
			{% for form in formset.forms %}
			{% if forloop.first %}
			<thead>
				<tr>
					<th>מוצר</th>
					<th>ספק</th>
					<th>יחידה</th>
					<th>ארוז/תפזורת</th>
					<th>אורגני</th>
					<th>גודל אריזה</th>
					<th>תיאור</th>
					<th>מחיר ליחידה</th>
					{% for field in form.visible_fields %}
					<th>{{ field.label|capfirst }}</th>
					{% endfor %}
				</tr>
			</thead>
			{% endif %}
			<tr class="product {% cycle row1,row2 %}">
				{% with form.instance.product as product %}
					<td>{{ product.product.name }}</td>
					<td>{{ product.product.supplier.name }}</td>
					<td>{{ product.product.unit }}</td>
					<td>{{ product.product.get_packaged_display }}</td>
					<td>{{ product.product.get_organic_display }}</td>
					<td class="package_size">{{ product.product.package_size }}</td>
					<td class="description">{{ product.product.description }}</td>
					<td>{{ product.price_including_VAT|multiply:user.get_profile.tariff.factor }}</td>
				{% endwith %}
				{% for field in form.visible_fields %}
					<td>{# Include the hidden fields in the form #}
					{% if forloop.first %}
						{% for hidden in form.hidden_fields %}
							{{ hidden }}
						{% endfor %}
					{% endif %}
					{{ field.errors.as_ul }}
					{{ field }}
					</td>
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
        <div class="form-actions">
            {{ formset.management_form }}
            <button type="submit" class="btn btn-primary">שמירה והמשך עריכה</button>
        </div>
    </form>
{% endblock %}

wsgi/django_foodcoop/templates/members/order_list.html
{% extends "site_base.html" %}

{% load foodcoop_extras %}

{% block extra_head %}
<script type="text/javascript">
jQ(document).ready(function() {
	var total = 0;
	jQ.each(jQ('td.total_price'), function(index, elem) {
		total = total + parseFloat(jQ(elem).html());
	});
	jQ('th#total').html(total.toFixed(2));
	
	jQ('#id_order_table').dataTable({
		"bSort": false,
		"aLengthMenu": [[-1], ["All"]],
	    "iDisplayLength": -1,
	    "sDom": 't',
	});
});
</script>
{% endblock %}

{% block body %}
<h3>סיכום הזמנה לחבר/ה</h3>
<h4>מכירה: {{ sale }}</h4>
<h4>חבר/ה: {{ member.get_full_name }}</h4>

<table id="id_order_table">
	<thead>
		<tr>
			<th></th>
			<th>מוצר</th>
			<th>ספק</th>
			<th>יחידה</th>
			<th>מחיר ליחידה</th>
			<th>הזמנה</th>
			<th>מחיר</th>
		</tr>
	</thead>
	<tbody>
		{% for order in object_list %}
			{% with order.product as product %}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{ product.name }}</td>
				<td>{{ product.product.supplier }}</td>
				<td>{{ product.product.unit }}</td>
                                <td>{{ product.price }}</td> 
				<td>{{ order.amount }}</td>
				<td class="total_price">{{ order.total_price }}</td>
			</tr>
			{% endwith %}
		{% endfor %}
		<tr>
			<th></th>
			<th>סה"כ</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th id="total"></th>
		</tr>
	</tbody>
</table>
{% endblock %}

wsgi/django_foodcoop/templates/members/test.html
{% extends "site_base.html" %}

{% load staticfiles %}
{% block head_title %}{{ sale }}{% endblock %}

{% block extra_head %}
<style>
table td.description {
	width: 250px;
}
select, input[type=text] {
	width: 40px;
}
textarea {
	width: 180px;
	height: 20px;
}
</style>
<script>
jQ(function() {
	jQ("#accordion").accordion({
	 collapsible: true
	});
 	jQ("#id_member_order_table").dataTable({
		"bSort": false,
		"aLengthMenu": [[-1], ["All"]],
	    "iDisplayLength": -1,
	    "sDom": 't',
	});
 	jQ.each(jQ("tr.product"), function(index, elem) {
 		package_size = parseFloat(jQ(elem).find('td.package_size').html());
 		if (package_size == 1) {
 			jQ(elem).find('input.conditional_disable').prop("readonly", true);
 		}
 	});
});
</script>

</script>
{% endblock %}

{% block body %}
	<h3>עריכת הזמנה</h3>
	<h4>מכירה: {{ sale }}</h4>
	<div id="accordion">
		<h3>הערות</h3>
		<div class="row">
			<iframe width="100%" height="350px" src="/announcesale/" frameBorder="0"></iframe>
		</div>
	</div>
	
    <form method="post" action="">
    {% csrf_token %}
    {% if formset.non_field_errors or formset.errors %}
    <p class="errornote">Please correct the errors below</p>
    {{ formset.non_field_errors.as_ul }}
	{% endif %}
    
    	{# taken from http://djangosnippets.org/snippets/1442/ #}
		<table id="id_member_order_table" class="form" border="1">
			{% for form in formset.forms %}
			{% if forloop.first %}
			<thead>
				<tr>
					<th>מוצר</th>
					<th>ספק</th>
					<th>יחידה</th>
					<th>ארוז/תפזורת</th>
					<th>אורגני</th>
					<th>גודל אריזה</th>
					<th>תיאור</th>
					<th>מחיר ליחידה</th>
					{% for field in form.visible_fields %}
					<th>{{ field.label|capfirst }}</th>
					{% endfor %}
				</tr>
			</thead>
			{% endif %}
			<tr class="product {% cycle row1,row2 %}">
				{% with form.instance.product as product %}
					<td>{{ product.product.name }}</td>
					<td>{{ product.product.supplier.name }}</td>
					<td>{{ product.product.unit }}</td>
					<td>{{ product.product.get_packaged_display }}</td>
					<td>{{ product.product.get_organic_display }}</td>
					<td class="package_size">{{ product.product.package_size }}</td>
					<td class="description">{{ product.product.description }}</td>
					<td>{{ product.price }}</td>
				{% endwith %}
				{% for field in form.visible_fields %}
					<td>{# Include the hidden fields in the form #}
					{% if forloop.first %}
						{% for hidden in form.hidden_fields %}
							{{ hidden }}
						{% endfor %}
					{% endif %}
					{{ field.errors.as_ul }}
					{{ field }}
					</td>
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
        <div class="form-actions">
            {{ formset.management_form }}
            <button type="submit" class="btn btn-primary">שמירה והמשך עריכה</button>
        </div>
    </form>
{% endblock %}